2025-05-16 14:10:48,150 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 14:12:27,465 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112660
2025-05-16 14:14:58,383 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112664
2025-05-16 14:15:42,212 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112665: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:16:01,641 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112666
2025-05-16 14:16:32,325 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112667: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:16:59,144 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112668: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:17:14,693 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112669: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 14:17:45,261 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112670: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:18:01,212 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112671
2025-05-16 14:18:18,030 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112672: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:18:47,834 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112673: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:19:18,162 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112674: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:19:50,109 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112675: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:20:11,013 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112676: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:20:40,405 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112677: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:21:01,195 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112678
2025-05-16 14:21:18,623 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112679: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:21:48,121 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112680: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:22:16,605 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112681: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:22:46,105 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112682: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:23:01,526 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112683
2025-05-16 14:23:18,349 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112684: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:23:49,876 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112685: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:24:15,010 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112686: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:24:45,013 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112687: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:25:01,876 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112688
2025-05-16 14:25:17,336 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112689: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 14:25:47,569 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112690: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:26:01,513 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112691
2025-05-16 14:26:17,158 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112692: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 14:26:43,352 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112693: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 14:27:02,137 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112694
2025-05-16 14:27:02,159 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba484d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,181 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba4a330>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,202 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0f110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,223 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0e090>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,244 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0f710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,265 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,286 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0dbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,308 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba4a240>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,329 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,350 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0ca40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,371 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0de50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,392 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0f380>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,413 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0efc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,434 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba4aea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,455 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0d910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,476 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0e2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,497 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0f4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,518 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:02,833 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 14:27:03,122 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
2025-05-16 14:27:03,143 - ERROR - Request Error http://15.235.15.230:14487/: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba48bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:03,770 - INFO - URL OK: https://cdn-3.nxplay.com.br/GLOBO_SP_TK/tracks-v1a1/mono.m3u8
2025-05-16 14:27:04,043 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 14:27:04,331 - INFO - URL OK: http://hls1.sua.tv:80/live/globosphd/s.m3u8
2025-05-16 14:27:05,284 - INFO - URL OK: http://metv.fun:80/4x6cXF/JDqRqj/90059.m3u8
2025-05-16 14:27:05,938 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/91431.m3u8: Status Code 404
2025-05-16 14:27:06,868 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/90034.m3u8
2025-05-16 14:27:07,924 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91421.m3u8
2025-05-16 14:27:08,817 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91435.m3u8
2025-05-16 14:27:09,707 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91463.m3u8
2025-05-16 14:27:10,603 - INFO - URL OK: http://metv.fun:80/4x6cXF/JDqRqj/90064.m3u8
2025-05-16 14:27:11,613 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/90019.m3u8
2025-05-16 14:27:12,649 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/95441.m3u8
2025-05-16 14:27:13,651 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91405.m3u8
2025-05-16 14:27:14,552 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91413.m3u8
2025-05-16 14:27:15,600 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/120082.m3u8
2025-05-16 14:27:16,496 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91443.m3u8
2025-05-16 14:27:17,391 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91445.m3u8
2025-05-16 14:27:18,286 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/95483.m3u8
2025-05-16 14:27:19,171 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/97396.m3u8
2025-05-16 14:27:20,052 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91456.m3u8
2025-05-16 14:27:20,623 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91460.m3u8: Status Code 404
2025-05-16 14:27:21,507 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/95448.m3u8
2025-05-16 14:27:22,497 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91461.m3u8
2025-05-16 14:27:23,536 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91467.m3u8
2025-05-16 14:27:24,530 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91470.m3u8
2025-05-16 14:27:25,411 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91471.m3u8
2025-05-16 14:27:26,315 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91473.m3u8
2025-05-16 14:27:27,310 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91477.m3u8
2025-05-16 14:27:28,199 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91479.m3u8
2025-05-16 14:27:28,220 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0c7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,241 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0ce90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,262 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0f410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,283 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0cb30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,304 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba49490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,325 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba48110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,345 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0ee40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,366 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0eea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,386 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,407 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0eb40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,428 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba4a180>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,449 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba48b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,470 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0cce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,490 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0e480>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,511 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0d5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,532 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba0ed50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,552 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba48710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,573 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9cba481d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 14:27:28,870 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 14:27:29,118 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
